# Generated by Django 4.1.7 on 2023-04-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0002_qr_titulo_alter_qr_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qr',
            name='data',
            field=models.ImageField(upload_to=''),
        ),
    ]
