# Generated by Django 4.1.7 on 2023-04-23 21:58

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0003_alter_qr_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qr',
            name='data',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[500, 300], upload_to=''),
        ),
    ]
