# Generated by Django 4.1.7 on 2023-04-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0005_alter_qr_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='qr',
            name='user',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
