# Generated by Django 4.1.7 on 2023-04-25 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0008_alter_qr_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qr',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
