# Generated by Django 4.1.7 on 2023-04-25 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0009_alter_qr_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qr',
            old_name='user',
            new_name='usuario',
        ),
    ]
